# Generated by Django 5.0.7 on 2025-09-22 18:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StandingOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Name/description of the standing order', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('payment_method', models.CharField(choices=[('wallet', 'Wallet Balance'), ('mpesa', 'M-Pesa Direct'), ('both', 'Wallet then M-Pesa')], default='wallet', max_length=10)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('recipient_account', models.CharField(blank=True, help_text='Account number or reference', max_length=100, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('next_execution', models.DateTimeField()),
                ('last_execution', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('failed', 'Failed')], default='active', max_length=20)),
                ('total_executions', models.PositiveIntegerField(default=0)),
                ('successful_executions', models.PositiveIntegerField(default=0)),
                ('failed_executions', models.PositiveIntegerField(default=0)),
                ('max_executions', models.PositiveIntegerField(blank=True, help_text='Maximum number of executions (null for unlimited)', null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum total amount to be paid', max_digits=12, null=True)),
                ('retry_attempts', models.PositiveIntegerField(default=3)),
                ('retry_interval_hours', models.PositiveIntegerField(default=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standing_orders', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standing_orders', to='wallets.wallet')),
            ],
            options={
                'verbose_name': 'Standing Order',
                'verbose_name_plural': 'Standing Orders',
                'db_table': 'standing_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StandingOrderExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_method_used', models.CharField(blank=True, max_length=10, null=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('standing_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='standing_orders.standingorder')),
            ],
            options={
                'verbose_name': 'Standing Order Execution',
                'verbose_name_plural': 'Standing Order Executions',
                'db_table': 'standing_order_executions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='standingorder',
            index=models.Index(fields=['user', 'status'], name='standing_or_user_id_7a2693_idx'),
        ),
        migrations.AddIndex(
            model_name='standingorder',
            index=models.Index(fields=['next_execution'], name='standing_or_next_ex_9e1ad2_idx'),
        ),
        migrations.AddIndex(
            model_name='standingorder',
            index=models.Index(fields=['status', 'next_execution'], name='standing_or_status_fa12fb_idx'),
        ),
        migrations.AddIndex(
            model_name='standingorder',
            index=models.Index(fields=['created_at'], name='standing_or_created_629338_idx'),
        ),
        migrations.AddIndex(
            model_name='standingorderexecution',
            index=models.Index(fields=['standing_order', 'created_at'], name='standing_or_standin_60fff4_idx'),
        ),
        migrations.AddIndex(
            model_name='standingorderexecution',
            index=models.Index(fields=['status'], name='standing_or_status_56f51d_idx'),
        ),
        migrations.AddIndex(
            model_name='standingorderexecution',
            index=models.Index(fields=['next_retry_at'], name='standing_or_next_re_3dfe1f_idx'),
        ),
    ]
